# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: 
      - main
      - develop

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    name: Lint 
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
      - name: GolangCI Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52.2
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.20"    

    - name: Build
      run: go build -v ./...

    - name: Test
      run: make test
